version: '3'

services:
  app:
    container_name: setup-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=4001
    ports:
      - 4001:4001